### PR TITLE
set Content-Type to json

### PR DESCRIPTION
**Pull request by kenany**
Fixes https://github.com/KenanY/strawpoll/issues/15

/cc @rfox90 for review?

### CODE REVIEW

**Comment by rfox90** [comment]
I'll take a better good shortly but looks good from mobile :)

**Comment by rfox90** [comment]
LGTM :+1:

**Comment by KenanY** [comment]
@rfox90 Thanks for the review!

Landed and pushed, but according to https://status.github.com/

> Our systems are working through a queue backlog. In the meantime, new pushes may take some time to show on GitHub.com.

Waiting on that before releasing 1.0.6.

**Comment by kenany** [comment]
Actually putting this in 1.1.0 since it's going in along with #13 which is a new feature. Not sure why I never published that before.

**Pull request closed without merging**
